### ISSUE TITLE
Publish a Nuget package of the Crowdin.Api

### ISSUE THREAD

**Issue by jasonleenaylor** [crowdin/crowdin-dotnet-client#4]
A Nuget package of the Crowdin.Api Project would be very useful.

I am building a tool based on the Crowdin.Api and it would be nice if the very good code that is sitting in develop was merged to master and a Nuget package published.

**Comment by andrii-bodnar** [comment]
Hello @jasonleenaylor! Thank you for the suggestion. 

We are going to publish a Nuget package in the nearest future.

**Comment by andrii-bodnar** [comment]
@jasonleenaylor published!
